---
- name: define php_fpm_pool_conf_path
  set_fact:
    php_fpm_pool_conf_path: "{{ __php_fpm_pool_conf_path }}"
  when: php_fpm_pool_conf_path is not defined

- name: define php_conf_path
  set_fact:
    php_conf_path: "{{ __php_conf_path }}"
  when: php_conf_path is not defined

- name: define php_fpm_pool_user
  set_fact:
    php_fpm_pool_user: "{{ __php_fpm_pool_user }}"
  when: php_fpm_pool_user is not defined

- name: define php_fpm_pool_group
  set_fact:
    php_fpm_pool_group: "{{ __php_fpm_pool_group }}"
  when: php_fpm_pool_group is not defined

- name: configure php-fpm pool (if enabled)
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^user.?=.+$"
      line: "user = {{ php_fpm_pool_user }}"
    - regexp: "^group.?=.+$"
      line: "group = {{ php_fpm_pool_group }}"

- name: configure php.ini
  lineinfile:
    dest: "{{ php_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^max_execution_time.?=.+$"
      line: "max_execution_time = {{ max_execution_time }}"
    - regexp: "^memory_limit.?=.+$"
      line: "memory_limit = {{ memory_limit }}"
    - regexp: "^upload_max_filesize.?=.+$"
      line: "upload_max_filesize = {{ upload_max_filesize }}"
    - regexp: "^post_max_size.?=.+$"
      line: "post_max_size = {{ post_max_size }}"
    - regexp: '.*date\.timezone.?=.+$'
      line: "date.timezone = {{ timezone }}"

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
    enabled: yes
