---
- name: install the development tools package group
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "@Development tools"
    - zlib-devel

- name: install pecl igbinary
  pear:
    name: pecl/igbinary
    state: present

- name: enable igbinary php extension
  copy:
    src: igbinary.ini
    dest: /etc/php.d/igbinary.ini
