---
- name: install epel and webtatic repositories
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - name: "{{ epel_repo }}"
    - name: "{{ webtatic_repo }}"

- name: install php-fpm and deps
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "{{ enable_repo }}"
  with_items:
    - "{{ php_packages }}"

- name: check igbinary module
  shell: php -m | grep -i igbinary
  register: igbinary_exist
  changed_when: false
  failed_when: false
  no_log: true

- include: php7-igbinary.yml
  static: false
  when:
    - igbinary_exist.rc == 1
    - php_version != 'php56'

- name: check memcached module
  shell: php -m | grep -i memcached
  register: memcached_exist
  changed_when: false
  failed_when: false
  no_log: true

- include: php7-memcached.yml
  static: false
  when:
    - memcached_exist.rc == 1
    - php_version != 'php56'
