---
- name: install the development tools package group
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "@Development tools"
    - zlib-devel

- name: download libmemcached
  get_url:
    url: https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz
    dest: /tmp/libmemcached-1.0.18.tar.gz

- name: extract libmemcached
  unarchive:
    src: /tmp/libmemcached-1.0.18.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure libmemcached
  command: ./configure
  args:
    chdir: /tmp/libmemcached-1.0.18

- name: run make for libmemcached
  command: make
  args:
    chdir: /tmp/libmemcached-1.0.18

- name: run make install for libmemcached
  command: make install
  args:
    chdir: /tmp/libmemcached-1.0.18

- name: git clone php-memcached-dev
  git:
    repo: https://github.com/php-memcached-dev/php-memcached
    dest: /tmp/php-memcached
    version: php7

- name: run phpize install
  command: phpize
  args:
    chdir: /tmp/php-memcached

- name: configure php-memcached
  command: ./configure --disable-memcached-sasl --enable-memcached-igbinary
  args:
    chdir: /tmp/php-memcached

- name: run make for php-memcached
  command: make
  args:
    chdir: /tmp/php-memcached

- name: run make install for php-memcached
  command: make install
  args:
    chdir: /tmp/php-memcached

- name: enable memcached php extension
  copy:
    src: z-memcached.ini
    dest: /etc/php.d/z-memcached.ini
