---
- name: install epel and webtatic repositories
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { item.name: epel_repo }
    - { item.name: webtatic_repo }

- name: install php-fpm and deps
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_packages }}"
