---
- name: install epel and webtatic repositories
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - name: "{{ epel_repo }}"
    - name: "{{ webtatic_repo }}"

- name: install php-fpm and deps
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: webtatic-testing
  with_items:
    - "{{ php_packages }}"
